---
title: Michael Shick
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: Michael Shick
- scope:
    path: ''
    type: projects
  values:
    author: Michael Shick
description: I'm a developer.
url: https://shick.us
author: Michael Shick
logo: "/assets/images/avatar.jpg"
destination: "./_site"
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
exclude:
- vendor
- node_modules
- package.json
- webpack.config.js
- postcss.config.js
- Gemfile
- Gemfile.lock
show_drafts: 
limit_posts: 0
future: false
unpublished: false
baseurl: ''
show_dir_listing: false
permalink: pretty
paginate_path: "/page:num"
quiet: false
verbose: false
liquid:
  error_mode: lax
repository: mshick/mshick.github.io
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jekyll-gist
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
compress_html:
  ignore:
    envs:
    - development
  blanklines: false
  profile: false
