site_name: Michael Shick
site_url: http://shick.us
site_description: Personal site hosted on GitHub Pages.
author_name: Michael Shick 
author_email: m@shick.us
github_author_name: mshick
github_author_url: https://github.com/mshick
github_repo_name: mshick.github.io
github_repo_url: https://github.com/mshick/mshick.github.io
